//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by GitVersion.
// 
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated> 
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyFileVersion("0.4.0.0")]
[assembly: AssemblyVersion("0.4.0.0")]
[assembly: AssemblyInformationalVersion("0.4.0-unstable.32+Branch.develop.Sha.4c78ab77eef73383e17ad300daf8bca98d0a8790")]