//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by GitVersion.
// 
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated> 
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyFileVersion("0.4.0.0")]
[assembly: AssemblyVersion("0.4.0.0")]
[assembly: AssemblyInformationalVersion("0.4.0-beta.1+0.Branch.release/v0.4.Sha.10102df1793fdc4c41b5cbbabd1615541457f19f")]