<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <SonarQubeExclude>true</SonarQubeExclude>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <CodeAnalysisRuleSet />
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <CodeAnalysisRuleSet />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ubiety.Stringprep.Core" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Ubiety.Xmpp.Core\Ubiety.Xmpp.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FluentAssertions" Version="8.6.0" />
    <PackageReference Update="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Update="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

</Project>
